server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://userDb:3306/user
    username: jemak
    password: pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet